#!/usr/bin/env python

"""
Convert single FASTQ files to FASTA + QUAL file pairs.
Written by Lucas Sinclair.
Kopimi.

Relevant discussion:
http://seqanswers.com/forums/showthread.php?t=3730

You can use this script from the shell like this:
$ ./fastq_to_fasta reads.fastq reads.fasta reads.qual
"""

# The libraries we need #
import sys, os
from Bio import SeqIO
# Check usage #
if len(sys.argv) < 2: sys.exit(sys.modules[__name__].__doc__)
# Get the shell arguments #
fq_path, fa_path, qa_path  = sys.argv[1], sys.argv[2], sys.argv[3]
# Check that the path is valid #
if not os.path.exists(fq_path): raise Exception("No file at %s." % fq_path)
# Do it #
SeqIO.convert(fq_path, "fastq", qa_path, "qual")
SeqIO.convert(fq_path, "fastq", fa_path, "fasta")
